### ISSUE TITLE
Errors attaching AddOns to plans and SubscriptionAddOn to Subscriptions

### ISSUE THREAD

**Issue by ehanderson** [recurly/recurly-client-python#118]
According to docs, I can create an `AddOn` like this:

``` python
addon1 = recurly.AddOn(
    add_on_code='ipaddresses',
    name='Extra IP Addresses',
    unit_amount_in_cents=200
)
print addon1
<recurly.AddOn object at 0x7f05b52da510>
```

However, when you call `plan.create_add_on(addon1)`, it errors due to `unit_amount_in_cents`:

``` python
  File "/home/vagrant/.virtualenvs/api/local/lib/python2.7/site-packages/recurly/__init__.py", line 833, in create_add_on
    return add_on.post(url)
  File "/home/vagrant/.virtualenvs/api/local/lib/python2.7/site-packages/recurly/resource.py", line 658, in post
    self.raise_http_error(response)
  File "/home/vagrant/.virtualenvs/api/local/lib/python2.7/site-packages/recurly/resource.py", line 683, in raise_http_error
    raise exc_class(response_xml)
recurly.errors.ValidationError: blank: add_on.unit_amount_in_cents can't be blank
```

To get around this issue, as shown in tests, it works to use a `recurly.Money()` resource object (although it feels wrong):

``` python
addon1 = recurly.AddOn(
    add_on_code='ipaddresses',
    name='Extra IP Addresses',
    unit_amount_in_cents=recurly.Money(4)
)
plan.create_add_on(addon1)
[<recurly.AddOn object at 0x7f05b52c1f50>]
```

Using the Money resource object here instead of an integer creates an issue creating/attaching a `SubscriptionAddOn` to a subscription:

``` python
sub_addon = recurly.SubscriptionAddOn(add_on_code=addon1.add_on_code)
my_sub.subscription_add_ons = [sub_addon]
s.save()
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/.virtualenvs/api/local/lib/python2.7/site-packages/recurly/resource.py", line 632, in save
    return self._update()
  File "/home/vagrant/.virtualenvs/api/local/lib/python2.7/site-packages/recurly/__init__.py", line 637, in _update
    return super(Subscription, self)._update()
  File "/home/vagrant/.virtualenvs/api/local/lib/python2.7/site-packages/recurly/resource.py", line 636, in _update
    return self.put(self._url)
  File "/home/vagrant/.virtualenvs/api/local/lib/python2.7/site-packages/recurly/resource.py", line 647, in put
    self.raise_http_error(response)
  File "/home/vagrant/.virtualenvs/api/local/lib/python2.7/site-packages/recurly/resource.py", line 683, in raise_http_error
    raise exc_class(response_xml)
recurly.errors.ValidationError: blank: subscription.subscription_add_ons[add_on_code=ipaddresses].unit_amount_in_cents can't be blank; invalid: subscription.subscription_add_ons[add_on_code=ipaddresses].add_on is invalid
```

To get around this error, you can override the `unit_amount_in_cents` with an integer when creating the `SubscriptionAddOn` as shown in docs:

``` python
my_sub.subscription_add_ons = []
tempaddon = recurly.SubscriptionAddOn()
tempaddon.add_on_code = 'ipaddresses'
tempaddon.quantity = 1
tempaddon.unit_amount_in_cents = 162
my_sub.subscription_add_ons.append(tempaddon)
my_sub.save()
```

This fixes the `unit_amount_in_cents` but not the `add_on` error: 

``` python
  File "/home/vagrant/.virtualenvs/api/local/lib/python2.7/site-packages/recurly/resource.py", line 632, in save
    return self._update()
  File "/home/vagrant/.virtualenvs/api/local/lib/python2.7/site-packages/recurly/__init__.py", line 637, in _update
    return super(Subscription, self)._update()
  File "/home/vagrant/.virtualenvs/api/local/lib/python2.7/site-packages/recurly/resource.py", line 636, in _update
    return self.put(self._url)
  File "/home/vagrant/.virtualenvs/api/local/lib/python2.7/site-packages/recurly/resource.py", line 647, in put
    self.raise_http_error(response)
  File "/home/vagrant/.virtualenvs/api/local/lib/python2.7/site-packages/recurly/resource.py", line 683, in raise_http_error
    raise exc_class(response_xml)
recurly.errors.ValidationError: invalid: subscription.subscription_add_ons[add_on_code=ipaddresses].add_on is invalid
```

I can recreate the error [here](https://github.com/recurly/recurly-client-python/blob/master/tests/test_resources.py#L161-L166), by removing the try and add `unit_amount_in_cents=200` to the AddOn

**Comment by bhelx** [comment]
Hey @ehanderson thanks for reporting.

You are right, it does feel wrong and I don't remember this being the case. I'm looking into it.

Also, kudos for laying this out so clearly!

**Comment by ehanderson** [comment]
Thanks for sure a quick response @bhelx . 
I've been looking into this a bit further:
The `recurly.Money(40)` part still seems like a potential bug; however, I have made the second `add_on` error occur in a few ways. 

In my scenario above, I think it was getting triggered for using an `add_on_code` that did not pair with an existing `Plan.AddOn` - so hopefully it is more of an error message issue as opposed to a bug issue.

Either way, thanks for taking a look!

**Comment by bhelx** [comment]
Okay, finally got a chance to dig into this.

Using the Money resource is the correct way to do it as you mentioned you read in the tests:
https://github.com/recurly/recurly-client-python/blob/master/tests/test_resources.py#L154

The way the python library works with serialization is that it maps a python level 'Resource' to an xml level tag. The resulting xml here for `unit_amount_in_cents` is:

```xml
<unit_amount_in_cents>
  <USD>200</USD>
</unit_amount_in_cents>
```

and using the Money resource allows changing the currency, etc. It's a strange/inconsistent part of the API because usually it's an integer and the currency is specified in another field such as transactions#create:

```xml
<amount_in_cents type="integer">1000</amount_in_cents>
<tax_in_cents type="integer">0</tax_in_cents>
<currency>USD</currency>
```

or invoice#post

```xml
<subtotal_in_cents type="integer">1200</subtotal_in_cents>
<tax_in_cents type="integer">0</tax_in_cents>
<total_in_cents type="integer">1200</total_in_cents>
<currency>USD</currency>
```

This is further complicated by the fact that the schema for add_ons in the subscription schema also follows this pattern:

```xml
<subscription_add_ons type="array">
  <subscription_add_on>
    <add_on_code>ipaddresses</add_on_code>
    <quantity>10</quantity>
    <unit_amount_in_cents>150</unit_amount_in_cents>
  </subscription_add_on>
</subscription_add_ons>
```

I want to say the best way forward would be to change the xml schema for add_ons so that it supports the method used everywhere else and deprecates the old method but it seems to be used in other places. Let me discuss with the team and report back here.

**Comment by NaughtyMC** [comment]
@bhelx We are running into the same issue - any update on this?

**Comment by bhelx** [comment]
@ehanderson @NaughtyMC Sorry, it looks like I never followed up on this thread. I had followed up on it elsewhere and forgot to come back and update.

In response to my last note:

> I want to say the best way forward would be to change the xml schema for add_ons so that it supports the method used everywhere else and deprecates the old method but it seems to be used in other places. Let me discuss with the team and report back here.

The reason this is different is because when creating a plan or an add on, you may want to define multiple prices for multiple currencies. For transactions, invoices, or subscription addons (for example) you only have one currency. I still think we could make this more consistent but that should at least answer why it is the way it is.

As for the solution to this problem, you should specify the currency when creating an add-on or a plan. The currencies and values can be passed in as kwargs to the `Money` class:

```python
plan = recurly.Plan.get('gold')

addon = recurly.AddOn(
    add_on_code='ipaddresses',
    name='Extra IP Addresses',
    unit_amount_in_cents=recurly.Money(USD=100,EUR=500) # 1$ or 5€ per IP address
)

plan.create_add_on(addon)
```

In general, where the XML API expects a currency list type, use `Money`. When the object in question has a separate `currency` attribute, use an `int`.
