### ISSUE TITLE
Improper refreshing of Resource objects after an action

### ISSUE THREAD

**Issue by pakal** [recurly/recurly-client-python#216]
When calling save() on a new Account (with attached BillingInfo), for example, the resource isn't properly updated, some of its attributes are stale. Among which "self.billing_info", which is still the old data sent to server, not the new one with updated tiemstamps and auto-generated tokens.

This is due to update_from_element() only deleting attributes from "cls.attributes",  a list which is often incomplete. Instead, the whole local data should be removed/replaced.

**Comment by bhelx** [comment]
I think your solution is correct, but I'm going to think about this one a little bit. I have to think about how other people are assuming it should to behave and any possible consequences of making this change. This wouldn't be a problem if we just returned a new object rather than mutating the one in place :(

**Comment by aaron-suarez** [comment]
Closing this issue because fixing it would require a redesign with breaking changes. The design choice to mutate the object in place was unfortunate, but will not be fixed until a major update to the library.
