### ISSUE TITLE
Subscription.plan_name not synchronized

### ISSUE THREAD

**Issue by pakal** [recurly/recurly-client-python#226]
This xml attribute is missing in "Subscription.attributes", and requires an extension of __getpath__, like so :

```
def __getpath__(self, name):
    if name == 'plan_code':
        return 'plan/plan_code'
    elif name == 'plan_name':
        return 'plan/name'
    else:
        return name
```

**Comment by bhelx** [comment]
So, given the xml looks like this:

```xml
<subscription href="https://bhelx.recurly.com/v2/subscriptions/414a325818789c9b992688491a8fe743">
  <!-- .... -->
  <plan href="https://bhelx.recurly.com/v2/plans/muwlysa6u3">
    <plan_code>gold</plan_code>
    <name>The Gold Plan</name>
  </plan>
  <uuid>414a325818789c9b992688491a8fe743</uuid>
  <!-- .... -->
</subscription>
```

One would assume you could just call the attributes on the plan object like this:

```python
sub = recurly.Subscription.get('44f83d7cba354d5b84812419f923ea96')
print(sub.plan.plan_code)  # => "gold"
print(sub.plan.name)          # => "The Gold Plan"
```

However this appears to not be the case on this library. Because it sees an `href` in the plan element, it builds a `relatitator`. It doesn't check to see if there are child elements.

``python
sub = recurly.Subscription.get('414a325818789c9b992688491a8fe743')
print(sub.plan) # => <function relatitator at 0x10cf252a8>
```

This is a function that can be called to fetch the resource. So the library would expect you to do it this way:

```python
sub = recurly.Subscription.get('414a325818789c9b992688491a8fe743')
plan = sub.plan()          # makes an http call to fetch the plan
print(plan.plan_code)  # => "gold"
print(plan.name)          # => "The Gold Plan"
```

I'm going to think about a way to solve this generically. If I can't think of a way to do that, I think your solution is a good compromise for this case.

**Comment by aaron-suarez** [comment]
I'm not really sure when or how this was fixed, but I just tried this out:
```
>>> print(recurly.__version__)
2.9.0
>>> sub = recurly.Subscription.get('4810fde9f3f29b244474e445d795cc78')
>>> print(sub)
<recurly.Subscription object at 0x109c5a990>
>>> print(sub.plan)
<recurly.Plan object at 0x109611b10>
>>> print(sub.plan.plan_code)
gold
>>> print(sub.plan.name)
Gold
```
Unless I misunderstand the initially reported problem, I believe this is issue must have resolved itself. I understand that @pakal no longer uses our library, so I'm not going to ask for any further testing from him. If anyone has any issues surrounding this, please feel free to re-open or comment, but I'm going to close this out for now.
